### ISSUE TITLE
Is it possible to show text?

### ISSUE THREAD

**Issue by CN91** [brenoprata10/ng2-image-viewer#10]
For a project I'm working on, I found your good looking viewer, the only thing is I would also like to add some text to the image that is showing. 

Is this already possible in the current version? 

Text as overlay, or under the picture or in the number-field (1/3)  under the picture?

**Comment by brenoprata10** [comment]
I believe it is possible, but you will have to implement it on the component that is calling my viewer, you can see on the documentation that i created 2 EventEmmiters, one when the user changes the image to the next one and another to the previous one, both of them will return the index of the image/pdf on the array, with that i believe you can correlate the position and the text you would like to show, the code would look like something like this:

HTML:
```
<app-image-viewer [images]="['iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==', 'https://picsum.photos/900/500/?random']"
[idContainer]="'idOnHTML'"
[loadOnInit]="true"
(onNext)="changedToNextImage($event)"></app-image-viewer>
```

TS:
```
// event is the index of the array
changedToNextImage(event) {

      this.textToDisplay = this.arrayWithText[event]
}
```

**Comment by brenoprata10** [comment]
Of course it depend of what data structure you have, but the idea would be the same on any perspective :)

**Comment by brenoprata10** [comment]
Closing issue, any question you can comment here again
