### ISSUE TITLE
How to convert PDF file into Base 64 and inject into the viewer

### ISSUE THREAD

**Issue by ghost** [brenoprata10/ng2-image-viewer#12]
Display pdf files of public link or in local attachment folder

**Comment by brenoprata10** [comment]
Could you provide more information?

**Comment by brenoprata10** [comment]
Closing issue due to lack of information

**Comment by ghost** [comment]
Hi Breno,
as i described in the issue, the ng2-image-viewer cant't display pdf files from an public link in internet or from a file in an folder inside the public folder of the angular app.
Can u provide me an example how i can convert the pdf file to base64?
By the way it would be nice if i can get the source code of your demo page on github.
Thank you for your support
Best regards
    On Friday, January 11, 2019, 2:40:19 PM GMT+1, Breno Prata <notifications@github.com> wrote:  
 
 
Closing issue due to lack of information

**Comment by brenoprata10** [comment]
I'll take a look at it, you can get some examples on this issue: #11

**Comment by brenoprata10** [comment]
Sorry it took soo long to help you, i'll take a look at it tonight and answer you today

**Comment by chakravorty** [comment]
@brenoprata10 is there any update on this? I'm facing the same issue providing s3 URLs of pdf but it is not being loaded.

**Comment by brenoprata10** [comment]
This not an issue from the component, you just have to convert the pdf file into base64 data, the component cannot render PDF via URLs, only images can be loaded like that, you can download a working example at #24
