### ISSUE TITLE
PDF view doesn't work on android mobiles

### ISSUE THREAD

**Issue by shaamcom83** [brenoprata10/ng2-image-viewer#13]
Hi Breno,
The plugin works fine for the ios devices. However when tested on android phones (Nexus 5X / API 28), the PDF view is not working. To cross check, your demo url is opened in the android's default browser(not chrome) and found that the PDF is not getting rendered.

When analysed more, it was found that the iframe containing blob protocol for the src attribute have some issues on cordova android. Though the allow-intent and allow-navigation tags are set to href="*", it is still not working.

Any thoughts.

**Comment by brenoprata10** [comment]
Good morning shaacom, 

I highly suggest chrome for this component, i'll be releasing a new version in a few days that will allow the user to download the pdf directly from the component if the browser does not support the iframe

Regards

**Comment by brenoprata10** [comment]
I'll be closing the issue because i just don't have the ways to proper test it and develop it, if possible open a pull request :)
