### ISSUE TITLE
How can I refresh or reload the ImageViewer?

### ISSUE THREAD

**Issue by shubhamdexbytes** [brenoprata10/ng2-image-viewer#14]
In my case,  I  want to reload the ImageViewer on click event. On click event I am changing the image src but In view part it does not show new image after click. I have checked jQuery Imageviewer documentation - http://ignitersworld.com/lab/imageViewer.html , here is the **refresh** method available.  https://i.imgur.com/s39sz7X.jpg

**Comment by brenoprata10** [comment]
Where do you wish to click and reload? on the next and previous buttons?

**Comment by shubhamdexbytes** [comment]
No, I have just custom icon, when I click on that image will be refresh or reload.

**Comment by brenoprata10** [comment]
Hello, sorry it took so long to answer you, have you tried injecting the component with the decorator @ViewChild and accessing the property 'viewer'? it would look like something like this:

your.component.html
```
<app-image-viewer #myViewer [images]="['iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==', 'https://picsum.photos/900/500/?random']"
[idContainer]="'idOnHTML'"
[loadOnInit]="true"></app-image-viewer>
```
your.component.ts
```
export class YourComponent {
    @ViewChild('myViewer') myViewer;

     onClickMethod() {
          this.myViewer.viewer.refresh();
     }
}
```

**Comment by brenoprata10** [comment]
If possible, give me your feedback so then a can close the issue o/

**Comment by shubhamdexbytes** [comment]
Thanks @brenoprata10 it's working now.
