### ISSUE TITLE
ReportItemComponent.html:16 ERROR ReferenceError: ImageViewer is not defined

### ISSUE THREAD

**Issue by Askold111188** [brenoprata10/ng2-image-viewer#15]
"@angular/animations": "~7.2.0",
ReportItemComponent.html:16 ERROR ReferenceError: ImageViewer is not defined
    at ImageViewerComponent.push../node_modules/ng2-image-viewer/ng2-image-viewer.umd.js.ImageViewerComponent.inicializarImageViewer (ng2-image-viewer.umd.js:214)
    at ImageViewerComponent.push../node_modules/ng2-image-viewer/ng2-image-viewer.umd.js.ImageViewerComponent.imagesChange (ng2-image-viewer.umd.js:187)
    at ImageViewerComponent.push../node_modules/ng2-image-viewer/ng2-image-viewer.umd.js.ImageViewerComponent.ngOnChanges (ng2-image-viewer.umd.js:98)
    at checkAndUpdateDirectiveDynamic (core.js:22020)
    at checkAndUpdateNodeDynamic (core.js:23281)
    at checkAndUpdateNode (core.js:23230)
    at debugCheckAndUpdateNode (core.js:23861)
    at debugCheckDirectivesFn (core.js:23821)
    at Object.eval [as updateDirectives] (ReportItemComponent.html:16)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:23813)
can you help me with it ?

**Comment by brenoprata10** [comment]
Could you provide more information? i can't help you with just the error console

**Comment by mmalia** [comment]
yes I can
When I try to use ng2-image-viewer I have similar error. I have done all from instruction

my component.html
 <div class="row">
            <div class="col-md-12">

                <app-image-viewer
                                  [images]="images"
                                  [idContainer]="'demo'"
                                  [loadOnInit]="false"
                                  [primaryColor]="'#0176bd'"
                                  [buttonsColor]="'#ffffff'"
                                  [buttonsHover]="'#0176bd'"
                                  [download]="true"
                                  [fullscreen]="true"
                                  [rotate]="true"
                                  [showOptions]="true"
                                  [defaultDownloadName]="'pdf'"
                                  [rotateRightTooltipLabel]="'Customizable: Rotate right'">
                </app-image-viewer>
            </div>
        </div>
____
in app.module
import { ImageViewerModule } from 'ng2-image-viewer';
imports: [
        ImageViewerModule,
    ],


and component.ts
import {Component, OnInit} from '@angular/core';
import {BasePDF} from "./basePDF";

@Component({
    selector: 'app-report-item',
    templateUrl: './report-item.component.html',
    styleUrls: ['./report-item.component.scss'],

})
export class ReportItemComponent implements OnInit {
    public images = [];

    constructor(private route: ActivatedRoute) {
    }

    ngOnInit() {
        this.id = this.route.snapshot.paramMap.get("id");
        this.images.push(BasePDF.PDF);
    }

}

**Comment by mmalia** [comment]
"dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "ng2-image-viewer": "^2.0.1",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },

**Comment by mmalia** [comment]
for icon and jqwery I used cdn url

**Comment by mmalia** [comment]
Maybe it does not work with angular 7.2?

**Comment by brenoprata10** [comment]
I never tested it on 7.2 before i'll take a look at it tonight, meanwhile, is it possible to send me your project?

**Comment by shubhamdexbytes** [comment]
@mmalia I got the same issue, This was JS path issue and I solved it.
remember include CSS and JS file in angular.json instead of angular-cli.json
Could you please open your angular.json file of your project and find your included files path

**Find this**

`"styles": [
    "../node_modules/ng2-image-viewer/imageviewer.scss"
],

"scripts": [
    "../node_modules/ng2-image-viewer/imageviewer.js"
],`

**replaced with**

`"styles": [
    "node_modules/ng2-image-viewer/imageviewer.scss"
],

"scripts": [
    "node_modules/ng2-image-viewer/imageviewer.js"
],`

please remove ../ and let me know

**Comment by mmalia** [comment]
Thanks, it helped.
I have one more question, does not it support IE and Edge brother?

**Comment by brenoprata10** [comment]
IE and Edge have limited support, the pdf viewer won't work, but the images will render without any problem

**Comment by brenoprata10** [comment]
I'll be closing the issue now that your problem has been resolved
