### ISSUE TITLE
component loading issue

### ISSUE THREAD

**Issue by krakapuzlis** [brenoprata10/ng2-image-viewer#16]
Hello,
I'm having and issue when trying to implement this image viewer.
Css classes loads, but it seems that .js or even jquery is making me get errors.
> ERROR ReferenceError: "$ is not  defined"
```
<div class="container">
    <app-image-viewer
      [images]="['https://picsum.photos/900/500/?image=1016', 'https://picsum.photos/900/500/?image=668']"
      [idContainer]="'idOnHTML'"
      [loadOnInit]="'demo'">
</app-image-viewer>
</div>
```

**Comment by brenoprata10** [comment]
Hello,

Please check if jquery is really installed on your app, you can take a look at some examples at issue: #11

**Comment by brenoprata10** [comment]
Please give me some feedback if possible, i'll be closing the issue tomorrow
