### ISSUE TITLE
CSS class 'tooltip' conflicts with bootstrap

### ISSUE THREAD

**Issue by reberinformatik** [brenoprata10/ng2-image-viewer#17]
In bootstrap there is a class 'tooltip'. This causes the buttons not to be displayed when bootstrap is used. Would it be possible to use a different name for the CSS class?

**Comment by brenoprata10** [comment]
Good afternoon,

I'll be changing the class name next week

**Comment by brenoprata10** [comment]
Good night,

As you can see from commit :https://github.com/brenoprata10/ng2-image-viewer/commit/a36329779fa5cd30fb9bede7f07348a0c7e6ea90

I just released a new version on npm as well, try again on version 2.0.2 and give your feedback as soon as possible.

Thx for your support

**Comment by reberinformatik** [comment]
Good morning Breno,
updated npm to v2.0.2 and it is now working together with Bootstrap.
Thank you!
