### ISSUE TITLE
lazy loading for images

### ISSUE THREAD

**Issue by jbougaev** [brenoprata10/ng2-image-viewer#18]
In the case when we have a lot of heavy files, is it possible to lazy load images/pdfs and at the same time have a number of total files displayed a the bottom of the viewer?

**Comment by brenoprata10** [comment]
I can say that it does not support this behaviour in a easy way, but you can do some tweaks on the code to do so.

**Working with the Total Label with lazy behaviour:**
The line of code that changes the text on the bottom of the component is `this.wrapper.find('.total').html(this.totalImagens)`
Up above you can see that the variable `wrapper` is the one responsible to work with the viewer container overral, this variable is not private so you can call the same line and send the number  you would like to be displayed, like this:
`this.wrapper.find('.total').html(this.numberContainingTheTotalOfImages)`

**Working with the images with lazy behaviour:**
The component emits two EventEmmiters, each for when the user presses the next/previous buttons, i believe you can load the image you would like to display on the function called from these emmiters, and then change the input `images` of the component based on it, I think it would look like something like this:

**HTML:**
```
<app-image-viewer #viewer
[images]="['iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==']"
[idContainer]="'idOnHTML'"
[loadOnInit]="true"
(onNext)="loadNextImage($event)"></app-image-viewer>
```

**TS:**
```
@ViewChild('viewer') viewer;

loadNextImage(index) {
    this.httpClient.get('lazy request to load my images')
          .subscribe(base64image => {
                this.images = [base64image];
                this.viewer.wrapper.find('.total').html(this.numberContainingTheTotalOfImages)
    })
}
```

I did not run any of this code and i don't have enought time to do so, but i hope it helped you to at least get an ideia on the solution =)

**Comment by brenoprata10** [comment]
Please give me your feedback if possible o/

**Comment by jbougaev** [comment]
Thank you for your answer. What you suggested sounds reasonable. I'll try to implement that.

**Comment by brenoprata10** [comment]
I'll be closing the issue today, you can still leave comments here If you wish =)
