### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by jbougaev** [brenoprata10/ng2-image-viewer#19]
I've upgraded your project to Angular 7 (because I had multiple issues with gulp, node-sass, etc. compilation of the original version ). Now I have an issue when clicking on Next button. 

`core.js:15723 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at EmulatedEncapsulationDomRenderer2.push../node_modules/@angular/platform-browser/fesm5/platform-browser.js.DefaultDomRenderer2.removeChild (http://localhost:4200/vendor.js:68858:20)
    at DebugRenderer2.push../node_modules/@angular/core/fesm5/core.js.DebugRenderer2.removeChild (http://localhost:4200/vendor.js:60208:23)
    at http://localhost:4200/main.js:1002:32
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:2781:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:53209:33)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:2780:60)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.js:2553:47)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (http://localhost:4200/polyfills.js:2856:34)
    at ZoneTask.invoke (http://localhost:4200/polyfills.js:2845:48)
    at timer (http://localhost:4200/polyfills.js:4639:29)`

It happens on the line: 
`this.renderer.removeChild(container, iframeElement); `

I've tried to play with the container and actually for a container like
`const container = document.getElementsByClassName('iv-image-wrap').item(0);` 
instead of 
` const container = document.getElementById(this.idContainer);` 
it works and I don't get this error. But I get the same issue when I put an image-viewer to ng-bootstrap modal dialog. 

My question is have you encountered this error? What in your opinion could be the cause of this exception? 

Thank you

**Comment by brenoprata10** [comment]
Hi Julia,

This is kinda hard to reply, could you send me your package.json and the component your injecting the viewer?

**Comment by jbougaev** [comment]
Hi Breno,

You can find the package.json here: https://github.com/julia-bougaev/image-viewer/blob/master/package.json, and app.component.ts here https://github.com/julia-bougaev/image-viewer/blob/master/src/app/app.component.html, where I inject your original image-viewer without any change.

**Comment by brenoprata10** [comment]
Ok Julia, i'll take a look at it tonight o/

**Comment by jbougaev** [comment]
Hi Breno,

I've actually fixed my issues with ng-bootstrap modal dialog. The problem was that imageview.js by default adds a container 

`$(function () {
      if(!$body.length) $body = $('body');

      $body.append('<div id="iv-container">' + imageViewHtml + '<div class="iv-close"></div><div>');

    });`

and your code by default adds an iframe to this default container and not to ng-bootstrap template container (because, in this case, it's not the first occurrence of 'iv-image-wrap' as it's written in injetarIframe method: `const ivImageWrap = document.getElementsByClassName('iv-image-wrap').item(0);`).

I've commented out the adding of default container in imageviewer.js (because I think it is redundant as we still pass a container to this plugin) as well as changed `const container = document.getElementById(this.idContainer);` to 'const container = document.getElementsByClassName('iv-image-wrap').item(0);'. With these changes I don't get this exception as well as modal dialog works fine. Maybe you can find the better solution.

You can find all these changes in the branch I've mentioned above. Also, I've added a lazy loading functionality for documents.

**Comment by brenoprata10** [comment]
Hi Julia,

Did you changed the JS file directly from the node-modules directory?

Regards,

Breno Prata.

**Comment by brenoprata10** [comment]
If so, what happens if you delete the node-modules directory and run install command again? :p

**Comment by jbougaev** [comment]
If I understand you correctly, I have not deleted any js directory from node_modules. I am able to delete node_module directory and install all packages again and the app runs as expected. That is regarding my branch.  For your source code, I was not able to install packages, I got a lot of issues with gulp and node-sass.

**Comment by brenoprata10** [comment]
Very good, i'm aiming to release a new rework of this component, but i don't have enough time right now, stay tuned for when it comes out o/

**Comment by brenoprata10** [comment]
I'll be closing the issue now, thx for your support!
