### ISSUE TITLE
Update underlying ImageViewer to 2.0.0

### ISSUE THREAD

**Issue by neuhausf** [brenoprata10/ng2-image-viewer#20]
Sudhanshu Yadav has updated his image viewer. It would be great, if you could update your imageviewer.js to the latest version 😃 
https://github.com/s-yadav/iv-viewer/releases

**Comment by brenoprata10** [comment]
Thx a lot! 
I'll try to release a new version without jquery as well. o/

**Comment by brenoprata10** [comment]
I just managed to update the viewer, but i'll take more time to release the 3.0 version.
I'll be closing the issue now

**Comment by brenoprata10** [comment]
Good night!
I just released version [3.0](https://www.npmjs.com/package/ng2-image-viewer) o/
It's a lot faster now and no longer uses Jquery!

**Comment by brenoprata10** [comment]
I've created a quick tutorial for the upgrade, take a look at it as well
[Upgrading from versions prior to 3.0](https://github.com/brenoprata10/ng2-image-viewer/wiki/Upgrading-from-versions-prior-to-3.0)

**Comment by neuhausf** [comment]
Thank you, that's great news! We will try it out next week 😃
