### ISSUE TITLE
imageviewer.js is not adding while installing using npm

### ISSUE THREAD

**Issue by pateldips** [brenoprata10/ng2-image-viewer#23]
Hi 

In description it mentioned that, add "imageviewer.js", but it is not adding while install using npm. I copied the code and created it manually. 

After that i am getting below error.
Cannot read property 'load' of undefined
    at ImageViewerComponent.push../node_modules/ng2-image-viewer/ng2-image-viewer.umd.js.ImageViewerComponent.showImage 

Seems like the viewer is not initializing.

**Comment by brenoprata10** [comment]
The `imageviewer.js` is only needed to the versions prior to 3.0, if you're using the 3.0 >, you only need to run 
`$ npm install iv-viewer --save` and
`$ npm install ng2-image-viewer --save`

**Comment by brenoprata10** [comment]
Also take a look at [this wiki](https://github.com/brenoprata10/ng2-image-viewer/wiki/Upgrading-from-versions-prior-to-3.0)

**Comment by pateldips** [comment]
Thanks. i have removed it. i am using Angular 7. i am still getting below error.

Cannot read property 'load' of undefined
    at ImageViewerComponent.push../node_modules/ng2-image-viewer/ng2-image-viewer.umd.js.ImageViewerComponent.showImage

i put the image url like

[images]="['http://localhost:4200/assets/img/logoGroupInner.jpg']"

Can you please help me?

Thank you

**Comment by brenoprata10** [comment]
Can you send me the code that's calling the viewer?

**Comment by pateldips** [comment]
i followed below steps:
1) install using npm
2) import into the module.ts file
3) In component html file added below code.

<app-image-viewer [images]="['http://localhost:4200/assets/img/logoGroupInner.jpg']"
[idContainer]="'idOnHTML'"
[loadOnInit]="false"></app-image-viewer>

and run.

**Comment by brenoprata10** [comment]
Try using loadOnOnit=true

**Comment by pateldips** [comment]
thank you. that works. what if i have to load it from component.ts and refresh it.

**Comment by pateldips** [comment]
i am trying to implement this way.
1) Blank container on load
2) pass the value in [images]
3) refresh

On html i put code like this.

<app-image-viewer [images]="['imageSrc']"
[idContainer]="'idOnHTML'"
[loadOnInit]="true"></app-image-viewer>

assign value from component [ideally it is coming as base64 string from WebAPI]
this.imageSrc = "http://localhost:4200/assets/img/logoGroupInner.jpg";

It is spinning and not loading image. 

Can you please help me?

**Comment by brenoprata10** [comment]
Tonight i'll take a look at it and try to release a new version with the fix

**Comment by brenoprata10** [comment]
Good night, 
I just released the [3.0.4 version](https://www.npmjs.com/package/ng2-image-viewer)
Try again with it please.
If you're adding images on ngOnInit, then you can use the normal push, but if you're adding images lazily:
**Remember to add lazy images like this:**
```
this.images = [...this.images, newImage(Ex: https://picsum.photos/400/700/?random)];
```
**Don't**
```
this.images.push('https://picsum.photos/400/700/?random');
```

**Comment by brenoprata10** [comment]
Please give me your feedback if possible.

Regards.

**Comment by pateldips** [comment]
hi sorry for late reply. finally i get a chance to look into it.

Yes it is working now. Now, if i loads PDF into it [only one PDF at the same time, no image], i am seeing below error, along with debug info most probably you left on page.

ERROR TypeError: Cannot read property 'NaN' of undefined
    at ImageViewerComponent.push../node_modules/ng2-image-viewer/ng2-image-viewer.umd.js.ImageViewerComponent.getImagemAtual (vendor.js:455962)
    at ImageViewerComponent.push../node_modules/ng2-image-viewer/ng2-image-viewer.umd.js.ImageViewerComponent.isURlImagem

even though the error PDF still display it, but the horizontal scroll bar is missing, in case of zoom.

Thank you,

**Comment by pateldips** [comment]
i guess the bottom part is hiding the PDF horizontal scroll bar. 

Can you please fix it when you get chance?

Thank you,

**Comment by pateldips** [comment]
did you get a chance to look into the PDF scroll bar issue?

**Comment by brenoprata10** [comment]
I am not having enough time to take a look at it
