### ISSUE TITLE
Incompatibilidade com Versão 7.2.0 Angular

### ISSUE THREAD

**Issue by MaurilioDeveloper** [brenoprata10/ng2-image-viewer#24]
Olá Breno, tudo bem?

Estou tentando utilizar a biblioteca, mas estou tendo problema para carregar PDF, e quando clico no botão para mostrar apenas 'PDF', ele da erro 'Maximum call stack size exceeded'. Estou utilzando a versão '7.2.0' do Angular. Será que é algum problema de versão? Pois ele diz que preciso utilzar a versão '5.1.0' do 'rxjs', mas estou utilizando a versão '6.3.3' dele, que é compativel com a versão 7.2.0 do angular. Não consigo mudar de versão, a menos que eu mudasse para a versão 5 do angular.

Consegue me ajudar com este problema?

**Comment by brenoprata10** [comment]
Boa noite Maurilio, eu acabei de lançar uma [nova versão](https://www.npmjs.com/package/ng2-image-viewer), peço que teste novamente com ela.
Eu testei o seu PDF e aparentemente o BASE64 dele carregou normalmente no meu viewer.

Atenciosamente,

Breno Prata

PS: Por favor abra as issues em inglês da próxima vez, assim mantemos a comunicação na mesma lingua que a comunidade =)

**Comment by brenoprata10** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26099427/57887340-ad596f80-7805-11e9-9fbc-826c2513f2a5.gif)

Segue zip com o projeto do gif
[ng2-image-viewer-demo.zip](https://github.com/brenoprata10/ng2-image-viewer/files/3189050/ng2-image-viewer-demo.zip)
