### ISSUE TITLE
Sometimes image not load

### ISSUE THREAD

**Issue by MaurilioDeveloper** [brenoprata10/ng2-image-viewer#25]
Sometimes, the images not load, and pdf never works. And, when I set the property 'show only pdf', happen this error: 'Maximum call stack size exceeded'
Follow the example used:

Image -> https://www.ibe.edu.br/wp-content/uploads/2018/03/certificado-americana-1.jpg

PDF -> http://www.orimi.com/pdf-test.pdf

Obs: I'm using the version 3.0.4

<app-image-viewer *ngIf="showImageViewer"
          [images]="[image]"
          [idContainer]="'idOnHTML'"
          [loadOnInit]="true"></app-image-viewer>

**Comment by brenoprata10** [comment]
Are you converting the pdf to base 64 before sending it to the component?
How are you sending the images, with base 64 or via url? i need more detail about it

**Comment by MaurilioDeveloper** [comment]
I'm sending the images and PDF by URL.

For exemplo:
ImageURL -> https://www.ibe.edu.br/wp-content/uploads/2018/03/certificado-americana-1.jpg

PdfURL -> http://www.orimi.com/pdf-test.pdf

**Comment by brenoprata10** [comment]
You must send PDF as a base 64 data, only images are supported with URL, take a look at the zip i uploaded with a working example #24

**Comment by MaurilioDeveloper** [comment]
It works! Thank you for help me!
