### ISSUE TITLE
Pdf not working on EDGE Browser

### ISSUE THREAD

**Issue by MaurilioDeveloper** [brenoprata10/ng2-image-viewer#26]
Hello dear friend.

I'm using the EDGE browser, version 44, but the PDF not load. In the others browsers (Chrome, Firefox and Opera) works normally. 
The pdf file is a base64. 
In the component, load the page instead of pdf file.
There isn't error on the console browser.

Pdf test: http://www.orimi.com/pdf-test.pdf

Can you help me?

**Comment by brenoprata10** [comment]
So far the component is not compatible with EDGE, but it might be in the future, because microsoft'll be releasing a new EDGE version based on chromium
