### ISSUE TITLE
download doesn't appear

### ISSUE THREAD

**Issue by anakin59490** [brenoprata10/ng2-image-viewer#27]
![test](https://user-images.githubusercontent.com/16132965/59309490-f46f3f00-8ca3-11e9-95c3-517e545b15ef.jpg)
Hi,

I use ng2-image-viewer in modal : 
`<mat-dialog-content >`
    `<div class="row" *ngIf="media !== null">`
        `<div class="col-md-12">`
            `<h2>`
                `{{media.idaialertmedia}}`
            `</h2>`
            `<app-image-viewer [images]="[fileUrl]"`
                            `  [idContainer]="'idOnHTML'"`
                             ` [fullscreen]="false"`
                              `[loadOnInit]="true"`
                              `  [showPDFOnlyOption]="false">`
           ` </app-image-viewer>`
        `</div>`
`</div>`
...

The image is displayed but without download option....which is the most important for me...

[download]="true" doesn't change anything

Thank you in advance

**Comment by brenoprata10** [comment]
If you're using a URL image, the download option is replaced by a redirect option, if you wish to download the image, use base64 data
