### ISSUE TITLE
High dpi image not loading

### ISSUE THREAD

**Issue by divyareddy12** [brenoprata10/ng2-image-viewer#28]
Is there a limit on the size o base64 image that can be loaded.
On converting an image(4.96MB) to base64(12MB) and sending it to the component, there is a  'net::ERR_INVALID_URL' error

**Comment by brenoprata10** [comment]
It should not have any kind of size limit, how are you sending the base64 data? If you need a working demo you can check out this issue #24

**Comment by divyareddy12** [comment]
I am converting blob to base64 using FileReader's readAsDataURL

**Comment by brenoprata10** [comment]
Can you send me just the initial 100 characters of the PDF that you are sending to the component?

**Comment by brenoprata10** [comment]
Closing issue due to lack of information

**Comment by divyareddy12** [comment]
[image-viewer.zip](https://github.com/brenoprata10/ng2-image-viewer/files/3361225/image-viewer.zip)
Sorry for the delay.
Unfortunately, I can not share the actual image. But I have attached a project with a sample image.
I am converting a png image to base64 and passing it to the component.
