### ISSUE TITLE
DOMException when replacing PDF with images

### ISSUE THREAD

**Issue by limcheepei** [brenoprata10/ng2-image-viewer#32]
This exception occurs for the following steps:
1. Load a PDF into the viewer. Viewer can show PDF successfully.
2. Click a button and load an image into the viewer. Viewer failed, and console shows the following exception:
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Another scenario where both PDF and image are loaded into the same viewer also has this exception.
<app-image-viewer [images]="[base64doc, base64image]"
[idContainer]="'idOnHTML'"
[loadOnInit]="true"></app-image-viewer>

The image is stored as base64.

**Comment by brenoprata10** [comment]
You can check #24, there's an example of this use case :)

**Comment by brenoprata10** [comment]
I'll be closing for now, reopen if it does not work for you
