### ISSUE TITLE
Crashed on Mozilla Firefox on zoom in-out

### ISSUE THREAD

**Issue by sizilkrishna** [brenoprata10/ng2-image-viewer#41]
Hello, first of all thanks for this wonderful plugin which saved me days! I have one suggestion tho, how about a lite view like [this](https://artsandculture.google.com/asset/the-underwave-off-kanagawa-katsushika-hokusai/JgEdIdn4pME3Mw), which activates on **click** and zooms into **whole screen** instead of the a container.

Anyways back to the bug,

I tried zooming in and out on a image in **Mozilla Firefox**, it crashed repeatedly and throws the same error on multple images, try zoomin in-out [here](https://mgoart.web.app/arts/showcase/16261),

Here's the Stack,

`TypeError: el is undefined Stack trace: setStyle@http://localhost:4200/vendor.js:154870:13 setStyle@http://localhost:4200/vendor.js:152455:9 setStyle@http://localhost:4200/vendor.js:109212:9 ./node_modules/ng2-image-viewer/ng2-image-viewer.umd.js/</ImageViewerComponent.prototype.atualizarCorHoverIn@http://localhost:4200/vendor.js:172749:9 View_ImageViewerComponent_16/<@ng:///ImageViewerModule/ImageViewerComponent.ngfactory.js:279:19 handleEvent@http://localhost:4200/vendor.js:107309:82 callWithDebugContext@http://localhost:4200/vendor.js:108928:24 debugHandleEvent@http://localhost:4200/vendor.js:108563:12 dispatchEvent@http://localhost:4200/vendor.js:94396:16 renderEventHandlerClosure/<@http://localhost:4200/vendor.js:106241:16 decoratePreventDefault/<@http://localhost:4200/vendor.js:154632:38 invokeTask@http://localhost:4200/polyfills.js:3626:17 onInvokeTask@http://localhost:4200/vendor.js:103312:24 invokeTask@http://localhost:4200/polyfills.js:3625:41 runTask@http://localhost:4200/polyfills.js:3403:28 invokeTask@http://localhost:4200/polyfills.js:3700:24 invokeTask@http://localhost:4200/polyfills.js:4838:9 globalZoneAwareCallback@http://localhost:4200/polyfills.js:4864:17`

`"setStyle@https://mgoart.web.app/main-es2015.1b0fb64bcb9a8301e53b.js:1:443044\nsetStyle@https://mgoart.web.app/main-es2015.1b0fb64bcb9a8301e53b.js:1:635236\nCcuA/</r</t.prototype.atualizarCorHoverIn@https://mgoart.web.app/main-es2015.1b0fb64bcb9a8301e53b.js:1:264836\nEy/<@https://mgoart.web.app/main-es2015.1b0fb64bcb9a8301e53b.js:1:1049810\nhandleEvent@https://mgoart.web.app/main-es2015.1b0fb64bcb9a8301e53b.js:1:232971\nhandleEvent@https://mgoart.web.app/main-es2015.1b0fb64bcb9a8301e53b.js:1:244378\nYp@https://mgoart.web.app/main-es2015.1b0fb64bcb9a8301e53b.js:1:148271\nwb/<@https://mgoart.web.app/main-es2015.1b0fb64bcb9a8301e53b.js:1:226309\nXt/<@https://mgoart.web.app/main-es2015.1b0fb64bcb9a8301e53b.js:1:441226\ninvokeTask@https://mgoart.web.app/polyfills-es2015.0ef207fb7b4761464817.js:1:7001\nonInvokeTask@https://mgoart.web.app/main-es2015.1b0fb64bcb9a8301e53b.js:1:205749\ninvokeTask@https://mgoart.web.app/polyfills-es2015.0ef207fb7b4761464817.js:1:6914\nrunTask@https://mgoart.web.app/polyfills-es2015.0ef207fb7b4761464817.js:1:2499\ninvokeTask@https://mgoart.web.app/polyfills-es2015.0ef207fb7b4761464817.js:1:8006\ny@https://mgoart.web.app/polyfills-es2015.0ef207fb7b4761464817.js:1:20114\nk@https://mgoart.web.app/polyfills-es2015.0ef207fb7b4761464817.js:1:20358\n"`

**Comment by brenoprata10** [comment]
Hi o/
That's strange, considering the stack, it should not break on such an easy task, are you modifying the JS of the component or injecting it with `ViewChild`? if so, could you provide more info about that?

**Comment by brenoprata10** [comment]
closing due to no response
