### ISSUE TITLE
Doesn't work with Angular 7

### ISSUE THREAD

**Issue by MaccabeeY** [brenoprata10/ng2-image-viewer#45]
This seemed like it would have been the 'king' library to use!  Sadly, generates the following in Angular 7:

![image](https://user-images.githubusercontent.com/4692331/71004990-6fc50980-20a8-11ea-9332-53546801c274.png)

"this.viewer" is undefined

With this console error:

![image](https://user-images.githubusercontent.com/4692331/71005061-94b97c80-20a8-11ea-989e-736141f5c65c.png)

This is what gets rendered:

![image](https://user-images.githubusercontent.com/4692331/71005318-14474b80-20a9-11ea-8126-8101ac1c1c2d.png)

**Comment by brenoprata10** [comment]
Could you send me line of code you are using to load the component?

**Comment by MaccabeeY** [comment]
I would normally be glad to but the project had to move forward and we had to move on to using another image viewer so I no longer have  the original code we used with your library.  I can suggest that we tried a variety of configurations and although some worked "better" than others, ultimately it would just not fully "play nicely" with Angular 7.

If I can help resolve this for you further, let me know...
