### ISSUE TITLE
adding images files

### ISSUE THREAD

**Issue by Paul75** [brenoprata10/ng2-image-viewer#5]
Hello,

I want to know when I can add images files (with url) ?

Thanks

**Comment by brenoprata10** [comment]
You can't, it supports only base64 images, I suggest you to use http://ignitersworld.com/lab/imageViewer.html :)

**Comment by Paul75** [comment]
but only images your suggestions, not PDF I must have images, and PDF files....

**Comment by brenoprata10** [comment]
can't you use the base 64 format? you could convert the image URL, try this: https://stackoverflow.com/questions/41778434/javascript-convert-an-url-to-a-base64-image

**Comment by brenoprata10** [comment]
This week i'll be releasing a new version, the 2.0 version will allow you to add url images as well :)
