### ISSUE TITLE
Issue Loading image

### ISSUE THREAD

**Issue by bbehling** [brenoprata10/ng2-image-viewer#7]
I'm getting an error at line 72 in imageviewer.js, img is undefined.

Watching the network traffic, a request is never made to the image.

I'm using Angular 6, jQuery 3.3.1 and have verified the image URL is correct.

**Comment by brenoprata10** [comment]
It does not support image URL, it was created to support base 64 images, please, verify issue: https://github.com/brenoprata10/ng2-image-viewer/issues/5

**Comment by brenoprata10** [comment]
This week i'll be releasing a new version, the 2.0 version will allow you to add url images as well :)
