### ISSUE TITLE
missed image in styles

### ISSUE THREAD

**Issue by dentkachuk** [brenoprata10/ng2-image-viewer#8]
https://github.com/brenoprata10/ng2-image-viewer/blob/007a20f879ba8cf9f57fffc59d48312f44650d41/src/imageviewer.scss#L161

there are no this image

**Comment by brenoprata10** [comment]
I'll be releasing a new version in one week, i'll take a look at it :+1:

**Comment by brenoprata10** [comment]
This reference will be deleted this week on version 2.0, i am closing this issue for now, thanks for your support o/
