### ISSUE TITLE
Cant see the buttons

### ISSUE THREAD

**Issue by gfdeluca** [brenoprata10/ng2-image-viewer#9]
When it shows de component the buttons are active but cant see the icon image.

**Comment by brenoprata10** [comment]
Could you please post your code?

**Comment by brenoprata10** [comment]
I'll be closing the issue in one day due to inactivity, could you please give me some info about the problem?

**Comment by gfdeluca** [comment]
Sorry miss the mail.
The problem is white de version 9 and 11, I downgrade to version 8 and works all fine with the same code.

The line of code is:
```
<div class="row" id="image-container">
<app-image-viewer *ngIf="documentoForm.value.estado === 'ASOCIADO'" idContainer="image-container" class="col-md-6 mt-1 mb-3" [images]="[documentoForm.value.imageFile]" [primaryColor]="'#000000'"></app-image-viewer>
</div>
```

**Comment by brenoprata10** [comment]
Could you change your code to 
```
<div class="row" id="row-container">
<app-image-viewer *ngIf="documentoForm.value.estado === 'ASOCIADO'" idContainer="image-container" class="col-md-6 mt-1 mb-3" [images]="[documentoForm.value.imageFile]" [primaryColor]="'#000000'"></app-image-viewer>
</div>
```

**Comment by brenoprata10** [comment]
The component uses the id to set some data, maybe the duplicate ID 'image-container' is the cause of the issue, could you test it again?

**Comment by gfdeluca** [comment]
With 1.1.1 and your code:

<img width="688" alt="captura de pantalla 2018-12-12 a la s 16 23 17" src="https://user-images.githubusercontent.com/3706047/49893537-6a483a00-fe2a-11e8-9f6a-0d9121d96a21.png">

With version 1.0.8, cant see de image but yes the icons

**Comment by brenoprata10** [comment]
Could you post the console log of the `documentoForm.value.imageFile` property?

**Comment by brenoprata10** [comment]
Closed due to inactivity
